name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - librosa
    - sndfile
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
